--#SET TERMINATOR @

CREATE TABLE TMP.XML_SCHEMA_INFO LIKE HUBBLE.XML_SCHEMA_INFO @

INSERT INTO TMP.XML_SCHEMA_INFO SELECT * FROM HUBBLE.XML_SCHEMA_INFO @

DROP TABLE HUBBLE.XML_SCHEMA_INFO @

CREATE TABLE HUBBLE.XML_SCHEMA_INFO
( XML_SCHEMA_VERSION CHARACTER(3) NOT NULL
) IN TBLSPC1 INDEX IN INXSPC1
COMPRESS YES ADAPTIVE
ORGANIZE BY ROW @

CREATE UNIQUE INDEX HUBBLE.XPK_XML_SCHEMA_INFO ON HUBBLE.XML_SCHEMA_INFO
    (XML_SCHEMA_VERSION)
COMPRESS YES
ALLOW REVERSE SCANS
COLLECT SAMPLED DETAILED STATISTICS @

ALTER TABLE HUBBLE.XML_SCHEMA_INFO ADD CONSTRAINT XPK_XML_SCHEMA_INFO
    PRIMARY KEY (XML_SCHEMA_VERSION)
ENFORCED
ENABLE QUERY OPTIMIZATION @

COMMENT ON TABLE HUBBLE.XML_SCHEMA_INFO IS 'Information om xmlschema' @

COMMENT ON COLUMN HUBBLE.XML_SCHEMA_INFO.XML_SCHEMA_VERSION IS 'Version på xmlschema' @

INSERT INTO HUBBLE.XML_SCHEMA_INFO SELECT * FROM TMP.XML_SCHEMA_INFO @

DROP TABLE TMP.XML_SCHEMA_INFO @

