--#SET TERMINATOR @

INSERT INTO STUDERA.ADDITIONAL_TEXT_DESCR (WORD,LANGUAGE_ID,ADDITIONAL_TEXT) VALUES ('c++','sv','c-plusplus')@

INSERT INTO STUDERA.ADDITIONAL_TEXT_DESCR (WORD,LANGUAGE_ID,ADDITIONAL_TEXT) VALUES ('c++','en','c-plusplus')@
