--#SET TERMINATOR @

ALTER TABLE STUDERA.OCCURRENCE_APPLICATION_URL DROP CONSTRAINT C1_OCCURRENCE_APPLICATION_URL @
ALTER TABLE STUDERA.OCCURRENCE_APPLICATION_URL ADD CONSTRAINT C1_OCCURRENCE_APPLICATION_URL
    CHECK ((APPLICATION_URL IS NOT NULL) OR (APPLICATION_URL_ALT IS NOT NULL))
ENFORCED
ENABLE QUERY OPTIMIZATION @

ALTER TABLE STUDERA.OCCURRENCE_TUITION_FEE DROP CONSTRAINT C4_OCCURRENCE_TUITION_FEE @
ALTER TABLE STUDERA.OCCURRENCE_TUITION_FEE ADD CONSTRAINT C4_OCCURRENCE_TUITION_FEE
    CHECK ((FEE_REQUIRED = 0 AND FIRST_INSTALMENT_FEE = 0 AND TOTAL_FEE = 0) OR (FEE_REQUIRED = 1))
ENFORCED
ENABLE QUERY OPTIMIZATION @

ALTER TABLE NYA.COURSE_OFFERING_TUITION_FEE_DRAFT DROP CONSTRAINT C4_COURSE_OFFERING_TUITION_FEE_DRAFT @
ALTER TABLE NYA.COURSE_OFFERING_TUITION_FEE_DRAFT ADD CONSTRAINT C4_COURSE_OFFERING_TUITION_FEE_DRAFT
    CHECK ((FEE_REQUIRED = 0 AND FIRST_INSTALMENT_FEE = 0 AND TOTAL_FEE = 0) OR (FEE_REQUIRED = 1))
ENFORCED
ENABLE QUERY OPTIMIZATION @

